server:
    port: 8100
spring:
    application:
        name: auto
    datasource:
        url: jdbc:mysql://www.unont.com.ar:3306/Municba
        username: x077vm05_unont
        password: Altos1948
    jpa:
        hibernate:
            ddl-auto: update
        
        database: mysql
        show-sql: true
miapp:
    apiToken: https://turnero.auth.us-east-1.amazoncognito.com/oauth2/token
    test: https://turnostest.cba.gov.ar/api/Externa/turnos/agendados
    client_id: 3848nekvugefsce0irdqsj23ud
    client_secret: n3moa7estdcdlqk4abqm4t9ns6fmkl8g2ntmaose4ibdgeur8ut   

debug: false


