#client_id: 3848nekvugefsce0irdqsj23ud
#client_secret: n3moa7estdcdlqk4abqm4t9ns6fmkl8g2ntmaose4ibdgeur8ut
server:
    port: 8100
spring:
    application:
        name: auto
    datasource:
        url: jdbc:mysql://localhost:3306/muni
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: update
        
        database: mysql
        show-sql: true
miapp:
    api: https://turnero.auth.us-east-1.amazoncognito.com/oauth2
    test: https://turnostest.cba.gov.ar/api

    

debug: false


